services:
  - type: web
    name: bazzar-kline-fetcher # Имя твоего сервиса
    env: node # ⬅️ ВАЖНО: Указываем, что это Node.js
    plan: free
    region: singapore # ⬅️ Хороший выбор для Европы

    # Команды из нашего package.json
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"

    # Эндпоинт для проверки "здоровья"
    healthCheckPath: /health

    # ⬇️ СЮДА НУЖНО ДОБАВИТЬ СЕКРЕТЫ (см. ниже)
    envVars:
      # - key: SECRET_TOKEN
      #   fromSecret: true # ⬅️ См. инструкцию ниже
      # - key: UPSTASH_REDIS_REST_URL
      #   fromSecret: true
      # - key: UPSTASH_REDIS_REST_TOKEN
      #   fromSecret: true
      # - key: COIN_SIFTER_URL
      #   fromSecret: true
