# Blueprint for Render Deployment
# This file tells Render how to build and run the project.

services:
  # The Python Web Server (FastAPI)
  - type: web
    name: bazzar-kline-data-fetcher
    env: python
    plan: free # Use the free instance type
    region: frankfurt # Deploy in Europe to avoid geo-blocking
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: SECRET_TOKEN
        generateValue: true # Render will automatically generate a secure secret key –ê
